HABITATS = {
    "woodland": {"name": "Woodland", "emoji": "🌲"},
    "savanna": {"name": "Savanna", "emoji": "🌾"},
    "tropical": {"name": "Tropical", "emoji": "🌴"},
    "aquatic": {"name": "Aquatic", "emoji": "🐠"},
    "tundra": {"name": "Tundra", "emoji": "❄️"},
    "mythic": {"name": "Mythic", "emoji": "✨"},
    "spectral": {"name": "Spectral", "emoji": "👻"},
    "desert": {"name": "Desert", "emoji": "🏜️"},
}

# capacity, passive coins earned per animal per hour, breed time reduction, coin cost to upgrade
ENCLOSURE_LEVELS = {
    1: {"capacity": 3, "coins_per_animal_hr": 0, "breed_bonus": 0.00, "upgrade_cost": 0},
    2: {"capacity": 6, "coins_per_animal_hr": 3, "breed_bonus": 0.05, "upgrade_cost": 300},
    3: {"capacity": 10, "coins_per_animal_hr": 6, "breed_bonus": 0.15, "upgrade_cost": 800},
    4: {"capacity": 15, "coins_per_animal_hr": 12, "breed_bonus": 0.25, "upgrade_cost": 2000},
    5: {"capacity": 21, "coins_per_animal_hr": 21, "breed_bonus": 0.40, "upgrade_cost": 5000},
}

MAX_ENCLOSURE_LEVEL = 5

SPECIES = [
    # Common — encounter 60%, catch 90%, cost 20, decay 3/tick
    {
        "name": "Mouse",
        "emoji": "🐭",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Frog",
        "emoji": "🐸",
        "rarity": "common",
        "habitat": "tropical",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Hamster",
        "emoji": "🐹",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Duck",
        "emoji": "🦆",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Snail",
        "emoji": "🐌",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Chicken",
        "emoji": "🐔",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Pig",
        "emoji": "🐷",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Sheep",
        "emoji": "🐑",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Fish",
        "emoji": "🐟",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Ladybug",
        "emoji": "🐞",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    # Rare — encounter 25%, catch 60%, cost 60, decay 5/tick
    {
        "name": "Cat",
        "emoji": "🐱",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Dog",
        "emoji": "🐶",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Bunny",
        "emoji": "🐰",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Fox",
        "emoji": "🦊",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Penguin",
        "emoji": "🐧",
        "rarity": "rare",
        "habitat": "tundra",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Owl",
        "emoji": "🦉",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Deer",
        "emoji": "🦌",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Parrot",
        "emoji": "🦜",
        "rarity": "rare",
        "habitat": "tropical",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Hedgehog",
        "emoji": "🦔",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Raccoon",
        "emoji": "🦝",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    # Epic — encounter 12%, catch 35%, cost 80, decay 7/tick
    {
        "name": "Panda",
        "emoji": "🐼",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Bear",
        "emoji": "🐻",
        "rarity": "epic",
        "habitat": "woodland",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Koala",
        "emoji": "🐨",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Lion",
        "emoji": "🦁",
        "rarity": "epic",
        "habitat": "savanna",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Tiger",
        "emoji": "🐯",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Wolf",
        "emoji": "🐺",
        "rarity": "epic",
        "habitat": "tundra",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Gorilla",
        "emoji": "🦍",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Hippo",
        "emoji": "🦛",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Crocodile",
        "emoji": "🐊",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    {
        "name": "Flamingo",
        "emoji": "🦩",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 28,
    },
    # Legendary — encounter 3%, catch 10%, cost 200, decay 10/tick
    {
        "name": "Unicorn",
        "emoji": "🦄",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Dragon",
        "emoji": "🐉",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Peacock",
        "emoji": "🦚",
        "rarity": "legendary",
        "habitat": "tropical",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Eagle",
        "emoji": "🦅",
        "rarity": "legendary",
        "habitat": "tundra",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Giraffe",
        "emoji": "🦒",
        "rarity": "legendary",
        "habitat": "savanna",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Elephant",
        "emoji": "🐘",
        "rarity": "legendary",
        "habitat": "savanna",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Whale",
        "emoji": "🐋",
        "rarity": "legendary",
        "habitat": "aquatic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "T-Rex",
        "emoji": "🦖",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Mammoth",
        "emoji": "🦣",
        "rarity": "legendary",
        "habitat": "tundra",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Shark",
        "emoji": "🦈",
        "rarity": "legendary",
        "habitat": "aquatic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    # ── Tundra additions ───────────────────────────────────────────────────────
    {
        "name": "Polar Bear",
        "emoji": "🐻‍❄️",
        "rarity": "common",
        "habitat": "tundra",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Arctic Hare",
        "emoji": "🐇",
        "rarity": "common",
        "habitat": "tundra",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Seal",
        "emoji": "🦭",
        "rarity": "rare",
        "habitat": "tundra",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Musk Ox",
        "emoji": "🦬",
        "rarity": "rare",
        "habitat": "tundra",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Snow Leopard",
        "emoji": "🐆",
        "rarity": "epic",
        "habitat": "tundra",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    # ── Aquatic additions ──────────────────────────────────────────────────────
    {
        "name": "Jellyfish",
        "emoji": "🪼",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Shrimp",
        "emoji": "🦐",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Swan",
        "emoji": "🦢",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Otter",
        "emoji": "🦦",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Lobster",
        "emoji": "🦞",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.55,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Crab",
        "emoji": "🦀",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Pufferfish",
        "emoji": "🐡",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Dolphin",
        "emoji": "🐬",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Octopus",
        "emoji": "🐙",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Squid",
        "emoji": "🦑",
        "rarity": "rare",
        "habitat": "aquatic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    # ── Tropical additions ─────────────────────────────────────────────────────
    {
        "name": "Ant",
        "emoji": "🐜",
        "rarity": "common",
        "habitat": "tropical",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Sloth",
        "emoji": "🦥",
        "rarity": "rare",
        "habitat": "tropical",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Turtle",
        "emoji": "🐢",
        "rarity": "common",
        "habitat": "tropical",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Lizard",
        "emoji": "🦎",
        "rarity": "common",
        "habitat": "tropical",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Snake",
        "emoji": "🐍",
        "rarity": "rare",
        "habitat": "tropical",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Butterfly",
        "emoji": "🦋",
        "rarity": "rare",
        "habitat": "tropical",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    # ── Savanna additions ──────────────────────────────────────────────────────
    {
        "name": "Cow",
        "emoji": "🐄",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Donkey",
        "emoji": "🫏",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Horse",
        "emoji": "🐴",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Zebra",
        "emoji": "🦓",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Kangaroo",
        "emoji": "🦘",
        "rarity": "epic",
        "habitat": "savanna",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Rhino",
        "emoji": "🦏",
        "rarity": "epic",
        "habitat": "savanna",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    # ── Woodland additions ─────────────────────────────────────────────────────
    {
        "name": "Bee",
        "emoji": "🐝",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Skunk",
        "emoji": "🦨",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Dove",
        "emoji": "🕊️",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Wild Boar",
        "emoji": "🐗",
        "rarity": "epic",
        "habitat": "woodland",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Moose",
        "emoji": "🫎",
        "rarity": "legendary",
        "habitat": "woodland",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Squirrel",
        "emoji": "🐿️",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Badger",
        "emoji": "🦡",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    # ── Mythic additions ───────────────────────────────────────────────────────
    {
        "name": "Troll",
        "emoji": "🧌",
        "rarity": "common",
        "habitat": "mythic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Goblin",
        "emoji": "👺",
        "rarity": "common",
        "habitat": "mythic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Elf",
        "emoji": "🧝",
        "rarity": "rare",
        "habitat": "mythic",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Dodo",
        "emoji": "🦤",
        "rarity": "rare",
        "habitat": "mythic",
        "catch_rate": 0.55,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Pegasus",
        "emoji": "🐎",
        "rarity": "epic",
        "habitat": "mythic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Merperson",
        "emoji": "🧜",
        "rarity": "epic",
        "habitat": "mythic",
        "catch_rate": 0.30,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Sauropod",
        "emoji": "🦕",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    {
        "name": "Phoenix",
        "emoji": "🐦‍🔥",
        "rarity": "epic",
        "habitat": "mythic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    # ── Spectral additions ─────────────────────────────────────────────────────
    {
        "name": "Bat",
        "emoji": "🦇",
        "rarity": "common",
        "habitat": "spectral",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Imp",
        "emoji": "😈",
        "rarity": "rare",
        "habitat": "spectral",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Demon",
        "emoji": "👿",
        "rarity": "legendary",
        "habitat": "spectral",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    # ── Spectral ───────────────────────────────────────────────────────────────
    {
        "name": "Ghost",
        "emoji": "👻",
        "rarity": "common",
        "habitat": "spectral",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Zombie",
        "emoji": "🧟",
        "rarity": "common",
        "habitat": "spectral",
        "catch_rate": 0.85,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Vampire",
        "emoji": "🧛",
        "rarity": "rare",
        "habitat": "spectral",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Fairy",
        "emoji": "🧚",
        "rarity": "rare",
        "habitat": "spectral",
        "catch_rate": 0.55,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Witch",
        "emoji": "🧙",
        "rarity": "epic",
        "habitat": "spectral",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Genie",
        "emoji": "🧞",
        "rarity": "epic",
        "habitat": "spectral",
        "catch_rate": 0.30,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Skeleton King",
        "emoji": "💀",
        "rarity": "legendary",
        "habitat": "spectral",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    # ── Desert ─────────────────────────────────────────────────────────────────
    {
        "name": "Scorpion",
        "emoji": "🦂",
        "rarity": "common",
        "habitat": "desert",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Beetle",
        "emoji": "🪲",
        "rarity": "common",
        "habitat": "desert",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 5,
        "breed_time_hrs": 6,
    },
    {
        "name": "Camel",
        "emoji": "🐪",
        "rarity": "rare",
        "habitat": "desert",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Bactrian Camel",
        "emoji": "🐫",
        "rarity": "rare",
        "habitat": "desert",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Tarantula",
        "emoji": "🕷️",
        "rarity": "rare",
        "habitat": "desert",
        "catch_rate": 0.55,
        "catch_cost": 60,
        "hunger_decay": 4,
        "breed_time_hrs": 12,
    },
    {
        "name": "Roadrunner",
        "emoji": "🐦",
        "rarity": "epic",
        "habitat": "desert",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Llama",
        "emoji": "🦙",
        "rarity": "epic",
        "habitat": "desert",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 3,
        "breed_time_hrs": 24,
    },
    {
        "name": "Sand Drake",
        "emoji": "🐲",
        "rarity": "legendary",
        "habitat": "desert",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 2,
        "breed_time_hrs": 48,
    },
    # Quest-exclusive — catch_rate 0.0 keeps them out of the wild catch pool
    {
        "name": "Capybara",
        "emoji": "🦫",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.0,
        "catch_cost": 0,
        "hunger_decay": 7,
        "breed_time_hrs": 10,
    },
    {
        "name": "Axolotl",
        "emoji": "🫧",
        "rarity": "legendary",
        "habitat": "aquatic",
        "catch_rate": 0.0,
        "catch_cost": 0,
        "hunger_decay": 15,
        "breed_time_hrs": 36,
    },
    {
        "name": "Quetzal",
        "emoji": "🪶",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.0,
        "catch_cost": 0,
        "hunger_decay": 15,
        "breed_time_hrs": 48,
    },
]

# Weighted encounter probabilities per rarity
ENCOUNTER_WEIGHTS = {
    "common": 57,
    "rare": 25,
    "epic": 14,
    "legendary": 4,
}

RARITY_ORDER = ["common", "rare", "epic", "legendary"]

RARITY_LABELS = {
    "common": "Common ⬜",
    "rare": "Rare 🟦",
    "epic": "Epic 🟪",
    "legendary": "Legendary 🟨",
}

RARITY_SQUARE = {
    "common": "⬜",
    "rare": "🟦",
    "epic": "🟪",
    "legendary": "🟨",
}

# Breed costs by rarity pair (sorted tuple → cost, base_hours at 100 hunger).
# Max breed time = base_hours * 2 (at 0 hunger). Legendary×Legendary capped at 4h.
BREED_TABLE = {
    ("common", "common"): {"cost": 50, "hours": 0.5},
    ("common", "rare"): {"cost": 120, "hours": 0.75},
    ("rare", "rare"): {"cost": 200, "hours": 1.0},
    ("common", "epic"): {"cost": 250, "hours": 1.25},
    ("rare", "epic"): {"cost": 300, "hours": 1.5},
    ("epic", "epic"): {"cost": 400, "hours": 2.0},
    ("common", "legendary"): {"cost": 500, "hours": 1.25},
    ("rare", "legendary"): {"cost": 600, "hours": 1.5},
    ("epic", "legendary"): {"cost": 700, "hours": 2.0},
    ("legendary", "legendary"): {"cost": 800, "hours": 2.0},
}


def get_breed_params(rarity_a, rarity_b):
    key = tuple(sorted([rarity_a, rarity_b], key=lambda r: RARITY_ORDER.index(r)))
    return BREED_TABLE.get(key, {"cost": 200, "hours": 24})
