HABITATS = {
    "woodland": {"name": "Woodland", "emoji": "🌲"},
    "savanna": {"name": "Savanna", "emoji": "🌾"},
    "tropical": {"name": "Tropical", "emoji": "🌴"},
    "aquatic": {"name": "Aquatic", "emoji": "🐠"},
    "tundra": {"name": "Tundra", "emoji": "❄️"},
    "mythic": {"name": "Mythic", "emoji": "✨"},
}

# capacity, passive coins earned per animal per hour, breed time reduction, coin cost to upgrade
ENCLOSURE_LEVELS = {
    1: {"capacity": 3, "coins_per_animal_hr": 0, "breed_bonus": 0.00, "upgrade_cost": 0},
    2: {"capacity": 6, "coins_per_animal_hr": 1, "breed_bonus": 0.05, "upgrade_cost": 300},
    3: {"capacity": 10, "coins_per_animal_hr": 2, "breed_bonus": 0.15, "upgrade_cost": 800},
    4: {"capacity": 15, "coins_per_animal_hr": 4, "breed_bonus": 0.25, "upgrade_cost": 2000},
    5: {"capacity": 21, "coins_per_animal_hr": 7, "breed_bonus": 0.40, "upgrade_cost": 5000},
}

MAX_ENCLOSURE_LEVEL = 5

SPECIES = [
    # Common — encounter 60%, catch 90%, cost 20, decay 3/tick
    {
        "name": "Mouse",
        "emoji": "🐭",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Frog",
        "emoji": "🐸",
        "rarity": "common",
        "habitat": "tropical",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Hamster",
        "emoji": "🐹",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Duck",
        "emoji": "🦆",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Snail",
        "emoji": "🐌",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Chicken",
        "emoji": "🐔",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Pig",
        "emoji": "🐷",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Sheep",
        "emoji": "🐑",
        "rarity": "common",
        "habitat": "savanna",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Fish",
        "emoji": "🐟",
        "rarity": "common",
        "habitat": "aquatic",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Ladybug",
        "emoji": "🐞",
        "rarity": "common",
        "habitat": "woodland",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    # Rare — encounter 25%, catch 60%, cost 60, decay 5/tick
    {
        "name": "Cat",
        "emoji": "🐱",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Dog",
        "emoji": "🐶",
        "rarity": "rare",
        "habitat": "savanna",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Bunny",
        "emoji": "🐰",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Fox",
        "emoji": "🦊",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Penguin",
        "emoji": "🐧",
        "rarity": "rare",
        "habitat": "tundra",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Owl",
        "emoji": "🦉",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Deer",
        "emoji": "🦌",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Parrot",
        "emoji": "🦜",
        "rarity": "rare",
        "habitat": "tropical",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Hedgehog",
        "emoji": "🦔",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Raccoon",
        "emoji": "🦝",
        "rarity": "rare",
        "habitat": "woodland",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    # Epic — encounter 12%, catch 35%, cost 80, decay 7/tick
    {
        "name": "Panda",
        "emoji": "🐼",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Bear",
        "emoji": "🐻",
        "rarity": "epic",
        "habitat": "woodland",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Koala",
        "emoji": "🐨",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Lion",
        "emoji": "🦁",
        "rarity": "epic",
        "habitat": "savanna",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Tiger",
        "emoji": "🐯",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Wolf",
        "emoji": "🐺",
        "rarity": "epic",
        "habitat": "tundra",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Gorilla",
        "emoji": "🦍",
        "rarity": "epic",
        "habitat": "tropical",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Hippo",
        "emoji": "🦛",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Crocodile",
        "emoji": "🐊",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Flamingo",
        "emoji": "🦩",
        "rarity": "epic",
        "habitat": "aquatic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    # Legendary — encounter 3%, catch 10%, cost 200, decay 10/tick
    {
        "name": "Unicorn",
        "emoji": "🦄",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Dragon",
        "emoji": "🐉",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Peacock",
        "emoji": "🦚",
        "rarity": "legendary",
        "habitat": "tropical",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Eagle",
        "emoji": "🦅",
        "rarity": "legendary",
        "habitat": "tundra",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Giraffe",
        "emoji": "🦒",
        "rarity": "legendary",
        "habitat": "savanna",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Elephant",
        "emoji": "🐘",
        "rarity": "legendary",
        "habitat": "savanna",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Whale",
        "emoji": "🐋",
        "rarity": "legendary",
        "habitat": "aquatic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "T-Rex",
        "emoji": "🦖",
        "rarity": "legendary",
        "habitat": "mythic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Mammoth",
        "emoji": "🦣",
        "rarity": "legendary",
        "habitat": "tundra",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Shark",
        "emoji": "🦈",
        "rarity": "legendary",
        "habitat": "aquatic",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
]

# Weighted encounter probabilities per rarity
ENCOUNTER_WEIGHTS = {
    "common": 60,
    "rare": 25,
    "epic": 12,
    "legendary": 3,
}

RARITY_ORDER = ["common", "rare", "epic", "legendary"]

RARITY_LABELS = {
    "common": "Common ⬜",
    "rare": "Rare 🟦",
    "epic": "Epic 🟪",
    "legendary": "Legendary 🟨",
}

# Breed costs by rarity pair (sorted tuple → cost, base_hours at 100 hunger).
# Max breed time = base_hours * 2 (at 0 hunger). Legendary×Legendary capped at 4h.
BREED_TABLE = {
    ("common", "common"): {"cost": 50, "hours": 0.5},
    ("common", "rare"): {"cost": 120, "hours": 0.75},
    ("rare", "rare"): {"cost": 200, "hours": 1.0},
    ("common", "epic"): {"cost": 250, "hours": 1.25},
    ("rare", "epic"): {"cost": 300, "hours": 1.5},
    ("epic", "epic"): {"cost": 400, "hours": 2.0},
    ("common", "legendary"): {"cost": 500, "hours": 1.25},
    ("rare", "legendary"): {"cost": 600, "hours": 1.5},
    ("epic", "legendary"): {"cost": 700, "hours": 2.0},
    ("legendary", "legendary"): {"cost": 800, "hours": 2.0},
}


def get_breed_params(rarity_a, rarity_b):
    key = tuple(sorted([rarity_a, rarity_b], key=lambda r: RARITY_ORDER.index(r)))
    return BREED_TABLE.get(key, {"cost": 200, "hours": 24})
