SPECIES = [
    # Common — encounter 60%, catch 90%, cost 20, decay 3/tick
    {
        "name": "Mouse",
        "emoji": "🐭",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Frog",
        "emoji": "🐸",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Hamster",
        "emoji": "🐹",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Duck",
        "emoji": "🦆",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Snail",
        "emoji": "🐌",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Chicken",
        "emoji": "🐔",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Pig",
        "emoji": "🐷",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Sheep",
        "emoji": "🐑",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Fish",
        "emoji": "🐟",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    {
        "name": "Ladybug",
        "emoji": "🐞",
        "rarity": "common",
        "catch_rate": 0.90,
        "catch_cost": 20,
        "hunger_decay": 3,
        "breed_time_hrs": 6,
    },
    # Rare — encounter 25%, catch 60%, cost 60, decay 5/tick
    {
        "name": "Cat",
        "emoji": "🐱",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Dog",
        "emoji": "🐶",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Bunny",
        "emoji": "🐰",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Fox",
        "emoji": "🦊",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Penguin",
        "emoji": "🐧",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Owl",
        "emoji": "🦉",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Deer",
        "emoji": "🦌",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Parrot",
        "emoji": "🦜",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Hedgehog",
        "emoji": "🦔",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    {
        "name": "Raccoon",
        "emoji": "🦝",
        "rarity": "rare",
        "catch_rate": 0.60,
        "catch_cost": 60,
        "hunger_decay": 5,
        "breed_time_hrs": 12,
    },
    # Epic — encounter 12%, catch 35%, cost 80, decay 7/tick
    {
        "name": "Panda",
        "emoji": "🐼",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Bear",
        "emoji": "🐻",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Koala",
        "emoji": "🐨",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Lion",
        "emoji": "🦁",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Tiger",
        "emoji": "🐯",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Wolf",
        "emoji": "🐺",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Gorilla",
        "emoji": "🦍",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Hippo",
        "emoji": "🦛",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Crocodile",
        "emoji": "🐊",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    {
        "name": "Flamingo",
        "emoji": "🦩",
        "rarity": "epic",
        "catch_rate": 0.35,
        "catch_cost": 80,
        "hunger_decay": 7,
        "breed_time_hrs": 28,
    },
    # Legendary — encounter 3%, catch 10%, cost 200, decay 10/tick
    {
        "name": "Unicorn",
        "emoji": "🦄",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Dragon",
        "emoji": "🐉",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Peacock",
        "emoji": "🦚",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Eagle",
        "emoji": "🦅",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Giraffe",
        "emoji": "🦒",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Elephant",
        "emoji": "🐘",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Whale",
        "emoji": "🐋",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "T-Rex",
        "emoji": "🦖",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Mammoth",
        "emoji": "🦣",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
    {
        "name": "Shark",
        "emoji": "🦈",
        "rarity": "legendary",
        "catch_rate": 0.10,
        "catch_cost": 200,
        "hunger_decay": 10,
        "breed_time_hrs": 48,
    },
]

# Weighted encounter probabilities per rarity
ENCOUNTER_WEIGHTS = {
    "common": 60,
    "rare": 25,
    "epic": 12,
    "legendary": 3,
}

RARITY_ORDER = ["common", "rare", "epic", "legendary"]

RARITY_LABELS = {
    "common": "Common ⬜",
    "rare": "Rare 🟦",
    "epic": "Epic 🟪",
    "legendary": "Legendary 🟨",
}

# Breed costs by rarity pair (sorted tuple → cost, base_hours at 100 hunger).
# Max breed time = base_hours * 2 (at 0 hunger). Legendary×Legendary capped at 4h.
BREED_TABLE = {
    ("common", "common"): {"cost": 50, "hours": 0.5},
    ("common", "rare"): {"cost": 120, "hours": 0.75},
    ("rare", "rare"): {"cost": 200, "hours": 1.0},
    ("common", "epic"): {"cost": 250, "hours": 1.25},
    ("rare", "epic"): {"cost": 300, "hours": 1.5},
    ("epic", "epic"): {"cost": 400, "hours": 2.0},
    ("common", "legendary"): {"cost": 500, "hours": 1.25},
    ("rare", "legendary"): {"cost": 600, "hours": 1.5},
    ("epic", "legendary"): {"cost": 700, "hours": 2.0},
    ("legendary", "legendary"): {"cost": 800, "hours": 2.0},
}


def get_breed_params(rarity_a, rarity_b):
    key = tuple(sorted([rarity_a, rarity_b], key=lambda r: RARITY_ORDER.index(r)))
    return BREED_TABLE.get(key, {"cost": 200, "hours": 24})
