-- up
ALTER TABLE animals DROP COLUMN happiness;
ALTER TABLE animals DROP COLUMN level;
ALTER TABLE animals DROP COLUMN xp;

-- down
ALTER TABLE animals ADD COLUMN happiness INTEGER NOT NULL DEFAULT 100;
ALTER TABLE animals ADD COLUMN level      INTEGER NOT NULL DEFAULT 1;
ALTER TABLE animals ADD COLUMN xp         INTEGER NOT NULL DEFAULT 0;
